---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cypress
        image: cypress/included:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            while true; do
              cypress run  -P "/e2e/cypress/"
              sleep 30
            done
        volumeMounts:
        - name: git-source
          mountPath: /e2e
        # resources:
        #   requests:
        #     memory: "500Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "500Mi"
        #     cpu: "500m"
      initContainers:
      - image: k8s.gcr.io/git-sync:v3.0.1
        name: git-data
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/avinash-yamani-devops/cypress-test-demo.git
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_DEST
          value: cypress
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_USERNAME
          valueFrom:
            secretKeyRef:
              name: git-creds
              key: username
        - name: GIT_SYNC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: git-creds
              key: password
        volumeMounts:
        - name: git-source
          mountPath: /tmp/git
      volumes:
      - name: git-source
        emptyDir: {}
