apiVersion: batch/v1
kind: Job
metadata: 
  # generateName: argocd-cypress-test- 
  name: argocd-cypress-test
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    # argocd.argoproj.io/continue-on: always
spec:
  backoffLimit: 0
  # ttlSecondsAfterFinished: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cypress-test
        image: localhost:5000/avinash-cypress-test:v1.0.2
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - "cypress run || true"
