apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: nginx:stable-otel
        command:
        - sleep 30
