apiVersion: batch/v1
kind: Job
metadata:
   generateName: nginx-sleep-
   # annotations:
   #   argocd.argoproj.io/hook: Postsync
spec:
  # completions: 1
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: nginx:stable-otel
