apiVersion: batch/v1 
kind: Job 
metadata: 
  generateName: nginx-test- 
  annotations:
    argocd.argoproj.io/hook: PostSync 
    
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: nginx:otel
