apiVersion: batch/v1
kind: Job
metadata:
  name: nginx
  # generateName: nginx-sleep-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  # backoffLimit: 1
  # completions: 1
  ttlSecondsAfterFinished: 30000
  template:
    spec:
      containers:
      - name: jobtest
        image: nginx:latest
        command: ["echo", "job-test"] 
      restartPolicy: Never
