apiVersion: batch/v1
kind: Job
metadata: 
  name: argocd-cypress-test
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation, HookFailed
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cypress-test
        image: localhost:5000/avinash-cypress-test:v1.0.3
        imagePullPolicy: Always
