apiVersion: batch/v1
kind: Job
metadata:
  generateName: sleep
  annotations:
    # argocd.argoproj.io/sync-options: Replace=true
    # argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: nginx:otel
