apiVersion: batch/v1
kind: Job
metadata: 
  # generateName: argocd-cypress-test- 
  name: argocd-cypress-test
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cypress-test
        image: localhost:5000/avinash-cypress-test:v1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 512m
            memory: 1G
          requests:
            cpu: 256m
            memory: 512Mi
        args:
        - cypress run --record --browser chrome
        - exit 0
