apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: nginx:stable-otel
        command:
        - /bin/sh
        - -c
        args:
        - sleep 30
