apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase
spec:
  # ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: liquibase
        image: liquibase:alpine
        command:
        - /bin/bash
        - -c
        args:
        - liquibase
