apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: nginx:alpine
        command:
        - /bin/sh
        - -c
        args:
        - sleep 5
